### ISSUE TITLE
Error running bap-frag

### ISSUE THREAD

**Issue by liaojinyue** [caleblareau/bap#23]
Hi, thanks for the nice tool. I would like to use bap-frag tool to generate fragments.tsv from the Bam file. However, I encountered this error as shown below.  Could you provide insight into how to fix this? Thanks.

Jason

```
Fri May 01 17:16:57 HKT 2020: Starting bap-frag pipeline v0.6.5
Traceback (most recent call last):
  File "/usr/local/bin/bap-frag", line 11, in <module>
    load_entry_point('bap-atac', 'console_scripts', 'bap-frag')()
  File "/home/leetl/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/leetl/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/leetl/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/leetl/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/leetl/bap/bap/cli_bap_frag.py", line 99, in main
    bead_tag)
  File "/home/leetl/bap/bap/bapFragProjectClass.py", line 72, in __init__
    self.bap_version = get_distribution('bap').version
  File "/home/leetl/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/home/leetl/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/leetl/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/leetl/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bap' distribution was not found and is required by the application
```

**Comment by liaojinyue** [comment]
I made it work by manually specifying the version of bap ("v0.6.5") in bapFragProjectClass.py.

**Comment by caleblareau** [comment]
would you mind posting that code that you used to do this? I'd like to fix it

Also, for fragment processing, I'd recommend looking into sinto (https://timoast.github.io/sinto/) if you haven't already

**Comment by liaojinyue** [comment]
Hi, I bypassed the error by changing line 72 in bapFragProjectClass.py from 
`self.bap_version = get_distribution('bap').version`
to
`self.bap_version = "v0.6.5"`

and thanks for the suggestion.

**Comment by caleblareau** [comment]
Thanks— this error occurs when I changed the name for pypi but missed this. In v0.6.6 (now on PyPi), I’ve corrected this.
